logging:
  level:
    org.springframework:
        jdbc:
          datasource:
            init:
              ScriptUtils: debug

spring:
  jpa:
    database: postgresql
    hibernate:
      ddl-auto: none
  datasource:
    url: jdbc:postgresql://localhost:5432/dev
    username: postgres
    password: postgres